var client=HealthgennieRTC.createClient({mode:"rtc",codec:"vp8"});var localTracks={videoTrack:null,audioTrack:null};var remoteUsers={};var options={appid:null,channel:null,uid:null,token:null};$(()=>{var urlParams=new URL(location.href).searchParams;options.appid=urlParams.get("appid");options.channel=urlParams.get("channel");options.token=urlParams.get("token");if(options.appid&&options.channel){$("#appid").val(options.appid);$("#token").val(options.token);$("#channel").val(options.channel);$("#join-form").submit()}})
$("#join-form").submit(async function(e){e.preventDefault();$("#join").attr("disabled",!0);try{options.appid=$("#appid").val();options.token=$("#token").val();options.channel=$("#channel").val();await join();if(options.token){$("#success-alert-with-token").css("display","block")}else{$("#success-alert a").attr("href",`index.html?appid=${options.appid}&channel=${options.channel}&token=${options.token}`);$("#success-alert").css("display","block")}}catch(error){console.error(error)}finally{$("#leave").attr("disabled",!1)}})
$("#leave").click(function(){console.log("Leave button clicked!");leave()});async function join(){client.on("user-published",handleUserPublished);client.on("user-unpublished",handleUserUnpublished);[options.uid,localTracks.audioTrack,localTracks.videoTrack]=await Promise.all([client.join(options.appid,options.channel,options.token||null),HealthgennieRTC.createMicrophoneAudioTrack(),HealthgennieRTC.createCameraVideoTrack()]);localTracks.videoTrack.play("local-player");$("#local-player-name").text(`localVideo(${options.uid})`);await client.publish(Object.values(localTracks));console.log("publish success")}
$(document).on("click","#leave",function(){console.log("Leave button clicked!");leave()});async function leave(){for(trackName in localTracks){var track=localTracks[trackName];if(track){track.stop();track.close();localTracks[trackName]=undefined}}
remoteUsers={};$("#remote-playerlist").html("");await client.leave();$("#video-section").addClass("d-none");$("#controls").addClass("d-none");$("h3").removeClass("d-none");$("#accept-call").removeClass("d-none");$("#reject-call").removeClass("d-none");$("#join-form").addClass("d-none");console.log("Left the call successfully")}
async function subscribe(user,mediaType){await client.subscribe(user,mediaType);console.log(`Subscribed to user ${user.uid}, mediaType: ${mediaType}`);if(mediaType==="video"){const player=$(`
      <div id="player-wrapper-${user.uid}">
        <p class="player-name">remoteUser(${user.uid})</p>
        <div id="player-${user.uid}" class="player"></div>
      </div>
    `);$("#remote-playerlist").append(player);user.videoTrack.play(`player-${user.uid}`)}
if(mediaType==="audio"){user.audioTrack.play()}}
$(document).ready(function(){$("#accept-call").click(function(){console.log("Accept button clicked, triggering Join...");$("h3").addClass("d-none");$("#accept-call, #reject-call").addClass("d-none");$("#video-section, #controls").removeClass("d-none");$("#join").trigger("click")});$("#reject-call").click(function(){console.log("Reject button clicked, triggering Leave...");$("#leave").trigger("click")});$("#pause-video").click(function(){if(localTracks.videoTrack){if($(this).hasClass("paused")){localTracks.videoTrack.setEnabled(!0);$(this).removeClass("paused").html('<i class="bi bi-pause-fill"></i> Pause Video')}else{localTracks.videoTrack.setEnabled(!1);$(this).addClass("paused").html('<i class="bi bi-play-fill"></i> Resume Video')}}});$("#mute-audio").click(function(){if(localTracks.audioTrack){if($(this).hasClass("muted")){localTracks.audioTrack.setEnabled(!0);$(this).removeClass("muted").html('<i class="bi bi-mic-fill"></i> Unmute Audio')}else{localTracks.audioTrack.setEnabled(!1);$(this).addClass("muted").html('<i class="bi bi-mic-mute-fill"></i> Mute Audio')}}});$("#leave").click(function(){console.log("Leave button clicked, disconnecting...");leave()})});function handleUserPublished(user,mediaType){const id=user.uid;remoteUsers[id]=user;subscribe(user,mediaType)}
function handleUserUnpublished(user){const id=user.uid;delete remoteUsers[id];$(`#player-wrapper-${id}`).remove()}